name: crypto_keys
description: A library for doing cryptographic signing/verifying and encrypting/decrypting.
version: 0.3.0+2
homepage: https://github.com/appsup-dart/crypto_keys
funding:
 - https://github.com/sponsors/rbellens
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  pointycastle: ^4.0.0
  meta: ^1.16.0
  collection: ^1.19.1
  quiver: ^3.2.2

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
